# Generated by Django 2.2.4 on 2019-08-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LM', models.IntegerField(max_length=12, verbose_name='LM код')),
                ('barcode', models.IntegerField(max_length=20, verbose_name='Штрихкод')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('department', models.IntegerField(max_length=2, verbose_name='Номер отдела')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название склада')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=3, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaultroom.Products', verbose_name='Товар')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaultroom.Storages', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар на стоке',
                'verbose_name_plural': 'Товар на стоке',
                'ordering': ['storage'],
            },
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=3, verbose_name='Количество выданного товара')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время выдачи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaultroom.Products', verbose_name='Выданный товар')),
            ],
            options={
                'verbose_name': 'Выданный товар',
                'verbose_name_plural': 'Выданный товар',
                'ordering': ['-time'],
            },
        ),
    ]
