# Generated by Django 2.2.4 on 2019-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.IntegerField(unique=True, verbose_name='Номер чека')),
                ('post', models.CharField(choices=[('Доставка', 'Доставка'), ('Выдача', 'Выдача')], max_length=10, verbose_name='Пост')),
                ('comment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время выдачи')),
            ],
            options={
                'verbose_name': 'Выданный чек',
                'verbose_name_plural': 'Выданные чеки',
                'ordering': ['-time'],
            },
        ),
        migrations.AlterField(
            model_name='done',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество выданного товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='LM',
            field=models.IntegerField(verbose_name='LM код'),
        ),
        migrations.AlterField(
            model_name='products',
            name='barcode',
            field=models.IntegerField(verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='department',
            field=models.IntegerField(verbose_name='Номер отдела'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
