# Generated by Django 2.2.4 on 2019-10-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultroom', '0002_auto_20191008_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='pallet',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во паллет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control',
            name='comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Коментарий'),
        ),
    ]
