# Generated by Django 2.2.4 on 2019-10-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaultroom', '0004_auto_20191017_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время перемещения')),
                ('fromstorage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fromstorage', to='vaultroom.Storages', verbose_name='Откуда')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vaultroom.Products', verbose_name='Товар')),
                ('tostorage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tostorage', to='vaultroom.Storages', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Перемещенный товар',
                'verbose_name_plural': 'Перемещенный товар',
                'ordering': ['-time'],
            },
        ),
    ]
